CREATE TABLE boat_service_schema.nautical_route (
	id bigserial NOT NULL,
	departure_name varchar(255) NOT NULL,
	departure_latitude float8 NOT NULL,
	departure_longitude float8 NOT NULL,
	arrival_name varchar(255) NOT NULL,
	arrival_latitude float8 NOT NULL,
	arrival_longitude float8 NOT NULL,
	departure_datetime timestamp NOT NULL,
	arrival_datetime timestamp NOT NULL,
	CONSTRAINT nautical_route_pkey PRIMARY KEY (id)
);


-- car_service_schema.car_sellers definition

-- Drop table

-- DROP TABLE car_service_schema.car_sellers;

CREATE TABLE car_service_schema.car_sellers (
	id bigserial NOT NULL,
	car_seller varchar(255) NOT NULL,
	"location" varchar(255) NOT NULL,
	latitude float8 NOT NULL,
	longitude float8 NOT NULL,
	CONSTRAINT car_sellers_latitude_check CHECK (((latitude >= (('-90'::integer)::numeric)::double precision) AND (latitude <= ((90)::numeric)::double precision))),
	CONSTRAINT car_sellers_longitude_check CHECK (((longitude >= (('-180'::integer)::numeric)::double precision) AND (longitude <= ((180)::numeric)::double precision))),
	CONSTRAINT car_sellers_pkey PRIMARY KEY (id)
);


-- car_service_schema.cars definition

-- Drop table

-- DROP TABLE car_service_schema.cars;

CREATE TABLE car_service_schema.cars (
	id bigserial NOT NULL,
	car_model_name varchar(255) NOT NULL,
	car_seller_id int8 NOT NULL,
	CONSTRAINT cars_pkey PRIMARY KEY (id),
	CONSTRAINT fk_car_seller FOREIGN KEY (car_seller_id) REFERENCES car_service_schema.car_sellers(id) ON DELETE CASCADE
);

-- flight_service_schema.flight_info definition

-- Drop table

-- DROP TABLE flight_service_schema.flight_info;

CREATE TABLE flight_service_schema.flight_info (
	id int8 NOT NULL,
	departure_name varchar(100) NOT NULL,
	departure_latitude float8 NOT NULL,
	departure_longitude float8 NOT NULL,
	arrival_name varchar(100) NOT NULL,
	arrival_latitude float8 NOT NULL,
	arrival_longitude float8 NOT NULL,
	departure_datetime timestamp NOT NULL,
	arrival_datetime timestamp NOT NULL,
	CONSTRAINT flight_info_pkey PRIMARY KEY (id)
);


-- flight_service_schema.hotel_info definition

-- Drop table

-- DROP TABLE flight_service_schema.hotel_info;

CREATE TABLE flight_service_schema.hotel_info (
	id int8 NOT NULL,
	hotel_name varchar(255) NOT NULL,
	location_latitude float8 NOT NULL,
	location_longitude float8 NOT NULL,
	location_name varchar(255) NOT NULL,
	CONSTRAINT hotel_info_location_latitude_check CHECK (((location_latitude >= ('-90'::integer)::double precision) AND (location_latitude <= (90)::double precision))),
	CONSTRAINT hotel_info_location_longitude_check CHECK (((location_longitude <= (180)::double precision) AND (location_longitude >= ('-180'::integer)::double precision))),
	CONSTRAINT hotel_info_pkey PRIMARY KEY (id)
);


-- flight_service_schema.itinerary_info definition

-- Drop table

-- DROP TABLE flight_service_schema.itinerary_info;

CREATE TABLE flight_service_schema.itinerary_info (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	hotel_id int4 NOT NULL,
	CONSTRAINT itinerary_info_pkey PRIMARY KEY (id)
);
-- hotel_service_schema.hotel_info definition

-- Drop table

-- DROP TABLE hotel_service_schema.hotel_info;

CREATE TABLE hotel_service_schema.hotel_info (
	id int8 NOT NULL,
	hotel_name varchar(255) NOT NULL,
	location_name varchar(255) NOT NULL,
	location_latitude float8 NOT NULL,
	location_longitude float8 NOT NULL,
	CONSTRAINT hotel_info_pkey PRIMARY KEY (id)
);

-- itinerary_prosumer_schema.itinerary_info definition

-- Drop table

-- DROP TABLE itinerary_prosumer_schema.itinerary_info;

CREATE TABLE itinerary_prosumer_schema.itinerary_info (
	id serial4 NOT NULL,
	hotel_id int4 NOT NULL,
	CONSTRAINT itinerary_info_pkey PRIMARY KEY (id)
);

-- transportation_prosumer_schema.transportation definition

-- Drop table

-- DROP TABLE transportation_prosumer_schema.transportation;

CREATE TABLE transportation_prosumer_schema.transportation (
	id bigserial NOT NULL,
	departure_location varchar(255) NOT NULL,
	arrival_location varchar(255) NOT NULL,
	service_type varchar(255) NOT NULL,
	service_id int8 NOT NULL,
	departure_hotel_id int8 NULL,
	arrival_hotel_id int8 NULL,
	service_id2 int8 NULL,
	car_seller varchar(255) NULL,
	CONSTRAINT transportation_pkey PRIMARY KEY (id),
	CONSTRAINT unique_hotel_pair UNIQUE (departure_hotel_id, arrival_hotel_id)
);