# Where to load the FreeMarker templates from (default is 'classpath:/templates/')
spring.freemarker.template-loader-path=classpath:/templates/

# File extension for FreeMarker templates
spring.freemarker.suffix=.ftl

# Disable caching for development to reflect changes without restarting the app
spring.freemarker.cache=false

# Encoding for FreeMarker templates
spring.freemarker.charset=UTF-8

# Allow starting FreeMarker templates with # to suppress warnings
spring.freemarker.prefer-file-system-access=false

logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG
logging.level.feign.client=DEBUG
